#ifndef GAME_SERVER_COMPONENT_VOTE_MENU_TYPES_H
#define GAME_SERVER_COMPONENT_VOTE_MENU_TYPES_H

#include <base/tl/array.h>

#include <game/voting.h>

enum EVoteMenuPage
{
	PAGE_MENU = 0,
	PAGE_INVENTORY,
	PAGE_CHECK_ITEM,
	PAGE_CRAFT,
	PAGE_CRAFT_SELECTED,
	PAGE_EQUIPMENT,
	PAGE_TURRET,
	PAGE_TURRET_AMMO,
	PAGE_WORLDS,
	PAGE_COMMUNITY,
	PAGE_DIFFICULTY,
	PAGE_SKILLS,
	PAGE_SKILL_SELECT,
	PAGE_TRAITS,
	PAGE_QUESTS,
	PAGE_QUEST_DETAIL,
	PAGE_DUTIES,
	PAGE_ACHIEVEMENTS,
	PAGE_COMPENDIUM,
	PAGE_COMPENDIUM_ZOMBIE,
	PAGE_COMPENDIUM_ITEM,
	PAGE_COMPENDIUM_TURRET_AMMO,
	PAGE_SHOP,

	// MMO pages (keep at end for clarity)
	PAGE_ATTRIBUTES = 99,
	VOTE_PAGE_MMO_MENU = 100,
	VOTE_PAGE_MMO_BACKPACK = 101,
	VOTE_PAGE_MMO_ITEM = 102,
	VOTE_PAGE_MMO_EQUIP = 103,
	VOTE_PAGE_MMO_GROUP = 104,
	VOTE_PAGE_MMO_MAILBOX = 105,
	VOTE_PAGE_MMO_MAIL_READ = 106,
	VOTE_PAGE_MMO_SOCIAL = 107,
	VOTE_PAGE_MMO_LIFESTYLE = 108,
	VOTE_PAGE_MMO_PVP = 109,
	VOTE_PAGE_MMO_ECONOMY = 110,
	VOTE_PAGE_MMO_ACTIVITIES = 111,
	VOTE_PAGE_MMO_FRIENDS = 112,
	VOTE_PAGE_MMO_RANKING = 113,
	VOTE_PAGE_MMO_AUCTION = 114,
	VOTE_PAGE_MMO_GUILD = 115,
	VOTE_PAGE_MMO_MOUNT = 116,
	VOTE_PAGE_MMO_PET = 117,
	VOTE_PAGE_MMO_HOUSE = 118,
	VOTE_PAGE_MMO_MARRIAGE = 119,
	VOTE_PAGE_MMO_ENCHANT = 120,
	VOTE_PAGE_MMO_CHAT = 121,
	VOTE_PAGE_MMO_GUILD_WAR = 122,
	VOTE_PAGE_MMO_BOSS = 123,
	VOTE_PAGE_MMO_SHOP = 124,
	VOTE_PAGE_MMO_AUCTION_LIST = 125,
	VOTE_PAGE_MMO_AUCTION_SELL = 126,
	VOTE_PAGE_MMO_AUCTION_SELL_PRICE = 127,
	VOTE_PAGE_MMO_SHOP_LIST = 128,
	VOTE_PAGE_MMO_SHOP_ITEMS = 129,
	VOTE_PAGE_MMO_ENCHANT_SELECT = 130,
	VOTE_PAGE_MMO_FASHION_SELECT = 131,
	VOTE_PAGE_MMO_FRIENDS_LIST = 132,
	VOTE_PAGE_MMO_RANKING_LEVEL = 133,
	VOTE_PAGE_MMO_RANKING_GOLD = 134,
	VOTE_PAGE_MMO_GUILD_BROWSE = 135,
	VOTE_PAGE_MMO_GUILD_DETAIL = 136,
	VOTE_PAGE_MMO_GUILD_REQUESTS = 137,
	VOTE_PAGE_MMO_GUILD_MEMBERS = 138,
	VOTE_PAGE_MMO_RECYCLE = 139,
	VOTE_PAGE_MMO_RECYCLE_CONFIRM = 140,
};

struct SPlayerVote
{
	enum EVoteSelect
	{
		ITEMLIST = 0,
		ITEM,
		EQUIPMENT,
		NUM_SELECT,
	};

	struct SVoteOptions
	{
		char m_aDescription[VOTE_DESC_LENGTH];
		char m_aCommand[VOTE_CMD_LENGTH];
	};

	array<SVoteOptions> m_aVoteOptions;
	int m_LastPage;
	int m_Page;
	int m_Select[NUM_SELECT];
	bool m_Confirm;
	char m_aExtraText[VOTE_DESC_LENGTH];
	int m_SkillId;
	int m_QuestIdx;

	void Reset()
	{
		m_aVoteOptions.clear();
		m_LastPage = 0;
		m_Page = 0;
		m_Confirm = false;
		for(int i = 0; i < NUM_SELECT; i++)
			m_Select[i] = 0;
		m_aExtraText[0] = 0;
		m_SkillId = 0;
		m_QuestIdx = 0;
	}
};

#endif
